server:
  port: 8189
  servlet:
    context-path: /api

jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 3600000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: app_security
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS app_security
      connection-timeout: 10000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
